server:
  port: 3000
  origin:
    - 'http://localhost'

db:
  type: 'postgres'
  port: 5432
  database: 'nest-db'
  synchronize: false
  migrationsRun: true

jwt:
  expiresIn: 3600
  refreshExpiresIn: '7d'
