version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    container_name: nest-api
    image: nest-api:0.0.1
    user: '1000:1000'
    volumes:
      - .:/usr/src/app
    networks:
      - nest-network
    env_file: '.env'
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    depends_on:
      - db

  db:
    image: postgres:12.4
    container_name: nest-db
    ports:
      - 5432:5432
    networks:
      - nest-network
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: nest-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.24
    container_name: nest-pgadmin
    ports:
      - 6400:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - nest-network
    depends_on:
      - db

  mail:
    image: aeimer/mailhog-secure
    container_name: nest-mail
    restart: unless-stopped
    environment:
      MH_USER: dev
      MH_PWD: dev
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mail:/data/mailhog
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge

volumes:
  pgadmin:
    driver: local

  pgdata:
    driver: local

  mail:
    driver: local
